### ISSUE TITLE
Bungeecord error with Scoreboard disconnecting players

### ISSUE THREAD

**Issue by Eufranio** [byYottaFLOPS/EasyScoreboards#15]
```
12:04:19 [SEVERE] [Nynguus_] <-> DownstreamBridge <-> [Beta] - encountered exception
java.lang.IllegalArgumentException: Objective Test already exists in this scoreboard
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at net.md_5.bungee.api.score.Scoreboard.addObjective(Scoreboard.java:55)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:126)
    at net.md_5.bungee.protocol.packet.ScoreboardObjective.handle(ScoreboardObjective.java:62)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by jonas-peeters** [comment]
Ok, maybe it wasn't that good of an idea to name the objective "Test". I never changed it, but I'll fix it in the next version.

**Comment by Eufranio** [comment]
When? :/

**Comment by GershonR** [comment]
Also getting this on my BungeeCord

**Comment by Brend-Smits** [comment]
Can confirm that this is still an issue. 
Any update on this or is this project abandoned?

**Comment by Eufranio** [comment]
I've been using a custom scoreboard plugin, but I guess the dev is just a bit busy.

**Comment by jonas-peeters** [comment]
I found the time to setup a bungee cord network. Sadly I wasn't able to reproduce your error. In the newest version I just changed the name of the objective to "EasyScoreboard", which could possibly solve the error. Could you please inform me, if this fixes your error messages too.
If the error persists, could you give me more information about your BungeeCord version and other mods you have installed?

**Comment by Eufranio** [comment]
Test is not the cause, but there's another objective causing issues/disconnect:
https://hastebin.com/zixeretasu.lua

**Comment by jonas-peeters** [comment]
Finally fixed in the latest version. Thanks for all your help.
