### ISSUE TITLE
Server thread/ERROR

### ISSUE THREAD

**Issue by Coloryr** [byYottaFLOPS/EasyScoreboards#23]
[00:07:58] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task de_yottaflops_easyscoreboard-S-9 owned by Plugin{id=de_yottaflops_easyscoreboard, name=Easy Scoreboards, version=2.1.1, description=A plugin to easily create scoreboards for lobbys, source=D:\mods\【P】EasyScoreboards.jar}, but an error occured.
java.lang.ArrayIndexOutOfBoundsException: 0
at de.YottaFLOPS.EasyScoreboard.Commands.Countdown.CountdownStart.lambda$execute$0(CountdownStart.java:143) ~[CountdownStart.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.10.2-2281-5.2.0-BETA-2379]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2379]
at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:81) ~[SyncScheduler.class:1.10.2-2281-5.2.0-BETA-2379]
at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2379]
at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2379]
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_131]
at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2379]
at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:51) [SyncScheduler.class:1.10.2-2281-5.2.0-BETA-2379]
at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2281-5.2.0-BETA-2379]
at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:271) [SpongeMod.class:1.10.2-2281-5.2.0-BETA-2379]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_17_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635) [EventBus.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) [EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by Wissi** [comment]
Yeah I get a similar error in logs. Except these errors occur approx 30 times in log before the world can be started. It's almost the same everytime, just:

```
java.lang.NoSuchMethodError: me.rojo8399.placeholderapi.PlaceholderService.replacePlaceholders(Lorg/spongepowered/api/entity/living/player/Player;Ljava/lang/String;)Lorg/spongepowered/api/text/Text;
```

Example:
```
[23:24:42] [Server thread/ERROR] [Sponge/]: The Scheduler tried to run the task de_yottaflops_easyscoreboard-S-10 owned by Plugin{id=de_yottaflops_easyscoreboard, name=Easy Scoreboards, version=2.1.1, description=A plugin to easily create scoreboards for lobbys, source=/home/minecraft/multicraft/servers/server70279/./mods/plugins/EasyScoreboards.jar}, but an error occured.
java.lang.NoSuchMethodError: me.rojo8399.placeholderapi.PlaceholderService.replacePlaceholders(Lorg/spongepowered/api/entity/living/player/Player;Ljava/lang/String;)Lorg/spongepowered/api/text/Text;
	at de.YottaFLOPS.EasyScoreboard.Main.makeScoreboard(Main.java:194) ~[Main.class:?]
	at de.YottaFLOPS.EasyScoreboard.Main.setScoreboard(Main.java:340) ~[Main.class:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_121]
	at de.YottaFLOPS.EasyScoreboard.Main.updateAllScoreboards(Main.java:331) ~[Main.class:?]
	at de.YottaFLOPS.EasyScoreboard.Utils.Runnables.lambda$startPlaceholderTask$2(Runnables.java:85) ~[Runnables.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:81) ~[SyncScheduler.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2597]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_121]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:51) [SyncScheduler.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:271) [SpongeMod.class:1.10.2-2281-5.2.0-BETA-2597]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_30_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```
