### ISSUE TITLE
NoSuchMethodError: me.rojo8399.placeholderapi

### ISSUE THREAD

**Issue by Wissi** [byYottaFLOPS/EasyScoreboards#25]
This errors occur approx 40 times in log before the world can be started. It's the same everytime, just:

```
java.lang.NoSuchMethodError: me.rojo8399.placeholderapi.PlaceholderService.replacePlaceholders(Lorg/spongepowered/api/entity/living/player/Player;Ljava/lang/String;)Lorg/spongepowered/api/text/Text;
```

Example:
```
[23:24:42] [Server thread/ERROR] [Sponge/]: The Scheduler tried to run the task de_yottaflops_easyscoreboard-S-10 owned by Plugin{id=de_yottaflops_easyscoreboard, name=Easy Scoreboards, version=2.1.1, description=A plugin to easily create scoreboards for lobbys, source=/home/minecraft/multicraft/servers/server70279/./mods/plugins/EasyScoreboards.jar}, but an error occured.
java.lang.NoSuchMethodError: me.rojo8399.placeholderapi.PlaceholderService.replacePlaceholders(Lorg/spongepowered/api/entity/living/player/Player;Ljava/lang/String;)Lorg/spongepowered/api/text/Text;
	at de.YottaFLOPS.EasyScoreboard.Main.makeScoreboard(Main.java:194) ~[Main.class:?]
	at de.YottaFLOPS.EasyScoreboard.Main.setScoreboard(Main.java:340) ~[Main.class:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_121]
	at de.YottaFLOPS.EasyScoreboard.Main.updateAllScoreboards(Main.java:331) ~[Main.class:?]
	at de.YottaFLOPS.EasyScoreboard.Utils.Runnables.lambda$startPlaceholderTask$2(Runnables.java:85) ~[Runnables.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:81) ~[SyncScheduler.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2597]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_121]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:51) [SyncScheduler.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2281-5.2.0-BETA-2597]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:271) [SpongeMod.class:1.10.2-2281-5.2.0-BETA-2597]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_30_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by jonas-peeters** [comment]
It looks like if an update of the placeholder plugin to 4.0 recently caused their API to change. As a fast fix I would advise you to use the Version 3.11 (3.12 probably also working) of the Placeholder API if possible.

I'll update the plugin as soon as possible. Till then 3.11 should work.

**Comment by ziceptor** [comment]
The same problem.

**Comment by Wissi** [comment]
Thank yoou for your really fast response. It's working perfectly Fine now that we have reverted to placeholder API ver. 3.12 (v 3.12 is working fine)

Could you please not close this until you update the plugin so we can know when it's ready to update?

Again, thank you very much.

**Comment by jonas-peeters** [comment]
Should work now in the latest version (2.2)

If you have any problems feel free to re-open this thread or make a new one

**Comment by ziceptor** [comment]
Thank you!
